import {
  ProductIdMM,
  ProductIdAS,
  ProductIdAM,
  ProductIdCM,
  ProductIdRM,
  ProductIdIM,
  ProductIdFM,
  ProductIdHM,
} from "@weave-mui/icons-weave";

export const ACCOUNT_NAV = [
  "Home",
  "Products and services",
  "User Management",
  "Billing and orders",
  "Reporting",
  "Support",
  "Settings",
];

export const PAGE_TABS = [
  { id: "all", label: "All products and services" },
  { id: "updates", label: "Product Updates" },
  { id: "custom-install", label: "Custom install" },
  { id: "scheduled-updates", label: "Scheduled updates" },
  { id: "trials", label: "Trials" },
  { id: "hubs", label: "Hubs" },
];

export const MARKETPLACE_FILTERS = [
  { id: "all", label: "All" },
  { id: "apps", label: "Apps" },
  { id: "agents", label: "Agents" },
  { id: "templates", label: "Templates" },
  { id: "skills", label: "Skills" },
];

export const PRODUCTS = [
  {
    id: "3dsmax",
    name: "3ds Max",
    icon: ProductIdMM,
    description:
      "Autodesk® 3ds Max™ 2027.1 brings you new features and improvements to the modeling, animation, and rendering toolsets.",
    version: "2027",
    platform: "Win 64",
    language: "English",
    cta: "Download",
    desktop: true,
    installFootnote: "Installs latest version 2027.2.1",
  },
  {
    id: "advance-steel",
    name: "Advance Steel",
    icon: ProductIdAS,
    description:
      "Advance Steel 2026.1 includes new detailing tools, improved interoperability with Revit, and updated drawing styles.",
    version: "2026",
    platform: "Win 64",
    language: "English",
    cta: "Download",
    desktop: true,
    installFootnote: "Installs latest version 2026.1.2",
  },
  {
    id: "alias-concept",
    name: "Alias Concept",
    icon: ProductIdAM,
    description:
      "Alias Concept 2026 delivers updated sketch and concept modeling tools for automotive and product design workflows.",
    version: "2026",
    platform: "Win 64",
    language: "English",
    cta: "Download",
    desktop: true,
    installFootnote: "Installs latest version 2026.1.0",
  },
  {
    id: "autocad",
    name: "AutoCAD",
    icon: ProductIdCM,
    description:
      "AutoCAD 2026.1 includes faster drawing regeneration, trace collaboration updates, and improved markup import.",
    version: "2026",
    platform: "Win 64",
    language: "English",
    cta: "Download",
    desktop: true,
    installFootnote: "Installs latest version 2026.1.2",
  },
  {
    id: "revit",
    name: "Revit",
    icon: ProductIdRM,
    description:
      "Autodesk Revit 2026.1 brings performance improvements, new interoperability tools, and enhanced documentation workflows.",
    version: "2026",
    platform: "Win 64",
    language: "English",
    cta: "Download",
    desktop: true,
    installFootnote: "Installs latest version 2026.1.1",
  },
  {
    id: "inventor",
    name: "Inventor Pro",
    icon: ProductIdIM,
    description:
      "Inventor 2026.2 delivers new assembly productivity tools, expanded sheet metal features, and performance improvements.",
    version: "2026",
    platform: "Win 64",
    language: "English",
    cta: "Download",
    desktop: true,
    installFootnote: "Installs latest version 2026.2.1",
  },
  {
    id: "acc",
    name: "Autodesk Construction Cloud",
    icon: ProductIdHM,
    description:
      "Connect teams, workflows, and insights across the construction lifecycle in a common data environment.",
    version: null,
    platform: null,
    language: null,
    cta: "Access",
    desktop: false,
  },
  {
    id: "forma",
    name: "Forma",
    icon: ProductIdFM,
    description:
      "Cloud-powered conceptual design software that helps planning and design teams make fast, informed decisions.",
    version: null,
    platform: null,
    language: null,
    cta: "Access",
    desktop: false,
  },
];

export const MARKETPLACE_SOLUTIONS = [
  {
    id: "model-checker",
    name: "Model Checker Pro",
    category: "apps",
    vendor: "Autodesk validated partner",
    worksWith: ["Revit", "ACC"],
    status: "Deployed",
    blurb: "Automated model validation against BIM standards and org rules.",
  },
  {
    id: "docs-automator",
    name: "Docs Issue Automator",
    category: "apps",
    vendor: "Marketplace",
    worksWith: ["ACC"],
    status: "Approved",
    blurb: "Route and assign ACC issues from clash results and RFIs.",
  },
  {
    id: "bim-agent",
    name: "BIM Coordination Agent",
    category: "agents",
    vendor: "AI Agent",
    worksWith: ["Revit", "ACC"],
    status: "Approved",
    blurb: "Suggests coordination fixes and drafts issue packages across models.",
  },
  {
    id: "ai-labels",
    name: "AI Room Labeling Agent",
    category: "agents",
    vendor: "AI Agent",
    worksWith: ["Revit"],
    status: "Available",
    blurb: "Proposes and applies room labels across large Revit projects.",
  },
  {
    id: "mep-template",
    name: "MEP Starter Template Pack",
    category: "templates",
    vendor: "Marketplace",
    worksWith: ["Revit"],
    status: "Available",
    blurb: "Pre-built Revit families, views, and sheets for MEP workflows.",
  },
  {
    id: "acc-handover",
    name: "ACC Handover Template",
    category: "templates",
    vendor: "Autodesk",
    worksWith: ["ACC"],
    status: "Deployed",
    blurb: "Standard folder structure and issue types for project closeout.",
  },
  {
    id: "cost-skill",
    name: "Cost Estimation Skill",
    category: "skills",
    vendor: "Marketplace",
    worksWith: ["ACC", "Revit"],
    status: "Approved",
    blurb: "Extract quantities and map cost codes from model data.",
  },
  {
    id: "clash-skill",
    name: "Clash Triage Skill",
    category: "skills",
    vendor: "Marketplace",
    worksWith: ["Revit", "Navisworks"],
    status: "Available",
    blurb: "Prioritize clashes by trade, severity, and location for faster review.",
  },
];
