/** Tokens extracted from Figma VisD — Products & Solutions Redesign (node 2327:484295). */
export const VIS_D = {
  colors: {
    background: "#FFFFFF",
    backgroundPanel: "#F9F9F9",
    ink: "#000000",
    text: "#212121",
    textPrimary: "#3C3C3C",
    textMuted: "rgba(0, 0, 0, 0.6)",
    searchFill: "rgba(0, 0, 0, 0.04)",
    searchFillOnDark: "rgba(255, 255, 255, 0.12)",
    border: "rgba(0, 0, 0, 0.1)",
    divider: "#E5E5E5",
    accent: "#5F60FF",
    navActive: "#3C3C3C",
    link: "#0696D7",
    warning: "#FFC21A",
    panel: "#F2F2F2",
    rowDivider: "rgba(0, 0, 0, 0.1)",
    footerBg: "#DEDEDE",
    textLight: "rgba(0, 0, 0, 0.6)",
    disabled: "rgba(0, 0, 0, 0.38)",
  },
  spacing: {
    pageTop: 32,
    pageX: 27,
    sectionGap: 24,
    blockGap: 32,
    titleGap: 4,
    cardGap: 24,
    cardPadding: 24,
    filtersPadding: 16,
  },
  radius: {
    card: 8,
    field: 4,
    button: 4,
    filters: 8,
  },
  sizes: {
    fieldHeight: 40,
    globalHeaderHeight: 56,
    accountNavHeight: 40,
    cardMinHeight: 402,
  },
  font: {
    element: '"Artifakt Element", ArtifaktElement, Arial, sans-serif',
    legend: '"Artifakt Element", ArtifaktElement, Arial, sans-serif',
  },
  typography: {
    pageTitle: {
      fontFamily: '"Artifakt Element", ArtifaktElement, Arial, sans-serif',
      fontSize: "30px",
      fontWeight: 800,
      lineHeight: 1.2,
      letterSpacing: 0,
      color: "#000000",
    },
    bodyMedium: {
      fontSize: "16px",
      fontWeight: 400,
      lineHeight: 1.5,
      color: "#000000",
    },
    bodySmall: {
      fontSize: "14px",
      fontWeight: 400,
      lineHeight: 1.5,
      color: "#212121",
    },
    headlineSmall: {
      fontSize: "16px",
      fontWeight: 700,
      lineHeight: 1.5,
      color: "#000000",
    },
    // Section headings (e.g. Recently purchased) — Weave extra-bold tier (800).
    sectionTitle: {
      fontFamily: '"Artifakt Element", ArtifaktElement, Arial, sans-serif',
      fontSize: "20px",
      fontWeight: 800,
      lineHeight: 1.2,
      letterSpacing: 0,
      color: "#000000",
    },
    productDetailTitle: {
      fontFamily: '"Artifakt Element", ArtifaktElement, Arial, sans-serif',
      fontSize: "34px",
      fontWeight: 800,
      lineHeight: 1.2,
      letterSpacing: 0,
      color: "#000000",
    },
    label16Semi: {
      fontSize: "16px",
      fontWeight: 600,
      lineHeight: "20px",
    },
    label14Semi: {
      fontSize: "14px",
      fontWeight: 600,
      lineHeight: "18px",
    },
    label14Bold: {
      fontSize: "14px",
      fontWeight: 700,
      lineHeight: 1.5,
    },
    billingSummary: {
      fontFamily: '"Artifakt Element", ArtifaktElement, Arial, sans-serif',
      fontSize: "21px",
      fontWeight: 700,
      lineHeight: 1.25,
      color: "#000000",
    },
    billingCount: {
      fontFamily: '"Artifakt Element", ArtifaktElement, Arial, sans-serif',
      fontSize: "26px",
      fontWeight: 800,
      lineHeight: 1.2,
      color: "#212121",
    },
    smallprint: {
      fontSize: "12px",
      fontWeight: 400,
      lineHeight: 1.5,
      color: "#212121",
    },
    compact: {
      fontSize: "16px",
      fontWeight: 400,
      lineHeight: "22px",
      color: "#3C3C3C",
    },
  },
};
